config/routes.rb
Rails.application.routes.draw do
  resources :potins
  get 'static_pages/index'
  get 'static_pages/secret'
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/potin.rb
class Potin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/potins_controller.rb
class PotinsController < ApplicationController
  before_action :set_potin, only: %i[ show edit update destroy ]

  # GET /potins or /potins.json
  def index
    @potins = Potin.all
  end

  # GET /potins/1 or /potins/1.json
  def show
  end

  # GET /potins/new
  def new
    @potin = Potin.new
  end

  # GET /potins/1/edit
  def edit
  end

  # POST /potins or /potins.json
  def create
    @potin = Potin.new(potin_params)

    respond_to do |format|
      if @potin.save
        format.html { redirect_to potin_url(@potin), notice: "Potin was successfully created." }
        format.json { render :show, status: :created, location: @potin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @potin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /potins/1 or /potins/1.json
  def update
    respond_to do |format|
      if @potin.update(potin_params)
        format.html { redirect_to potin_url(@potin), notice: "Potin was successfully updated." }
        format.json { render :show, status: :ok, location: @potin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @potin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /potins/1 or /potins/1.json
  def destroy
    @potin.destroy

    respond_to do |format|
      format.html { redirect_to potins_url, notice: "Potin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_potin
      @potin = Potin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def potin_params
      params.require(:potin).permit(:titre, :contenu, :auteur)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end

  def contact
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/potins_helper.rb
module PotinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Endproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/#">Acceuil</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item nav-link">
                <a class="nav-link" href="/static_pages/team">Team</a>
              </li>
              <li class="nav-item nav-link">
                <a class="nav-link" href="/static_pages/contact">Contact</a>
              </li>
              <li class="nav-item nav-link">
                <ul>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Potins
                    </a>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item">
                        <% if current_user %>
                          <%= link_to "Afficher les Potins", potins_path, method: :get %>
                        <% end %>
                      </li>
                      <li class="dropdown-item">
                        <% if current_user %>
                          <%= link_to "Créer un Potin", new_potin_path, method: :get %>
                        <% end %>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class="nav-item nav-link">
                <ul>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Account
                    </a>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item">
                        <%# <a class="nav-link" href="/users/sign_up">Sign up</a> %>
                        <% if !current_user %>
                          <%# unless %>
                          <%= link_to "Sign up", new_user_registration_path %>
                        <% end %>
                      </li>
                      <li class="dropdown-item">
                        <%# <a class="nav-link" href="/users/sign_in">Sign in</a> %>
                        <% if !current_user %>
                          <%= link_to "Sign in", new_user_session_path %>
                        <% end %>
                      </li>
                      <li class="dropdown-item">
                        <%# <a class="nav-link" href="/users/sign_out">Sign out</a> %>
                        <% if current_user %>
                          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                        <% end %>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
            <span class="navbar-text">
              <% if current_user %>
                <%= link_to "Secret", static_pages_secret_path, method: :get %>
              <% end %>
            </span>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/potins/_form.html.erb
<%= form_with(model: potin) do |form| %>
  <% if potin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(potin.errors.count, "error") %> prohibited this potin from being saved:</h2>

      <ul>
        <% potin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titre, style: "display: block" %>
    <%= form.text_field :titre %>
  </div>

  <div>
    <%= form.label :contenu, style: "display: block" %>
    <%= form.text_area :contenu %>
  </div>

  <div>
    <%= form.label :auteur, style: "display: block" %>
    <%= form.text_field :auteur %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/potins/_potin.html.erb
<div id="<%= dom_id potin %>">
  <p>
    <strong>Titre:</strong>
    <%= potin.titre %>
  </p>

  <p>
    <strong>Contenu:</strong>
    <%= potin.contenu %>
  </p>

  <p>
    <strong>Auteur:</strong>
    <%= potin.auteur %>
  </p>

</div>

app/views/potins/edit.html.erb
<h1>Editing potin</h1>

<%= render "form", potin: @potin %>

<br>

<div>
  <%= link_to "Show this potin", @potin %> |
  <%= link_to "Back to potins", potins_path %>
</div>

app/views/potins/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Potins</h1>
<div id="potins">
  <% @potins.each do |potin| %>
    <%= render potin %>
    <p>
      <%= link_to "Show this potin", potin %>
    </p>
  <% end %>
</div>
<%= link_to "New potin", new_potin_path %>
<div class="container px-4 py-5" id="featured-3">
  <h2 class="pb-2 border-bottom">Liste des potins:</h2>
  <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
    <div class="feature col">
      <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
      </div>
      <h3 class="fs-2 text-body-emphasis">Featured title</h3>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi"><use xlink:href="#chevron-right"/></svg>
      </a>
    </div>
    <div class="feature col">
      <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
      </div>
      <h3 class="fs-2 text-body-emphasis">Featured title</h3>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi"><use xlink:href="#chevron-right"/></svg>
      </a>
    </div>
    <div class="feature col">
      <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
        <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
      </div>
      <h3 class="fs-2 text-body-emphasis">Featured title</h3>
      <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      <a href="#" class="icon-link">
        Call to action
        <svg class="bi"><use xlink:href="#chevron-right"/></svg>
      </a>
    </div>
  </div>
</div>
<p>app/views/potins/index.html.erb</p>

app/views/potins/new.html.erb
<h1>New potin</h1>

<%= render "form", potin: @potin %>

<br>

<div>
  <%= link_to "Back to potins", potins_path %>
</div>

app/views/potins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @potin %>

<div>
  <%= link_to "Edit this potin", edit_potin_path(@potin) %> |
  <%= link_to "Back to potins", potins_path %>

  <%= button_to "Destroy this potin", @potin, method: :delete %>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact Page</h1>
<p>This is the contact page content.</p>

app/views/static_pages/index.html.erb
<div class="px-4  text-center border-bottom">
  <h1 class="display-4 fw-bold text-body-emphasis">Des potins, rien que des potins</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">C'est ici que commence ton aventure sur ce site.</p>
    <p class="lead mb-4">Pour plus de facilité, tout ou presque se passe sur la Navbar. &#128521;</p>
  </div>
  <div class="overflow-hidden" style="max-height: 52vh;">
    <div class="container px-5">
      <img src="https://static8.depositphotos.com/1008939/939/i/600/depositphotos_9393392-stock-photo-gossip.jpg" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
    </div>
  </div>
</div>
<p>app/views/static_pages/index.html.erb</p>

app/views/static_pages/secret.html.erb
  <div class="px-4  text-center border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">Voici la "Page Secrète"</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Tu ne peux y avoir accès que depuis ton compte!</p>
      <p class="lead mb-4">Elle sert a faire toutes sortes d'expérimentations lors de la cration du site web.</p>
    </div>
    <div class="overflow-hidden" style="max-height: 52vh;">
      <div class="container px-5">
        <img src="https://images.unsplash.com/reserve/oIpwxeeSPy1cnwYpqJ1w_Dufer%20Collateral%20test.jpg?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1915&q=80" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
      </div>
    </div>
  </div>
<p>app/views/static_pages/secret.html.erb</p>

app/views/static_pages/team.html.erb
<h1>Team Page</h1>
<p>This is the team page content.</p>